# Build settings
[build]
  publish = "."
  command = ""

# Redirects for category pages
[[redirects]]
  from = "/category/:category"
  to = "/category.html?cat=:category"
  status = 200

# Redirects for search
[[redirects]]
  from = "/search"
  to = "/search.html?q=:splat"
  status = 200

# Redirects for admin
[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 200

# Redirects for article pages (clean URLs)
[[redirects]]
  from = "/*"
  to = "/article.html"
  status = 200
  conditions = { Path = ["/:slug"] } # Matches any path without a file extension (e.g., /my-slug)

# Prerender rule for social media bots
[[redirects]]
  from = "/*"
  to = "https://service.prerender.io/:splat"
  status = 200
  force = true
  conditions = { User-Agent = [
    "Twitterbot",
    "facebookexternalhit",
    "WhatsApp",
    "Googlebot",
    "bingbot",
    "LinkedInBot",
    "Slackbot",
    "TelegramBot",
    "Discordbot",
    "Applebot"
  ] }
  headers = { "X-Prerender-Token" = "${PRERENDER_TOKEN}" }

# Catch-all for SPA routing (fallback to index.html)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200